// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfXvXFG8nT7Ad7UWn8H99HOgfUZmDyM0Y',
    appId: '1:706848631529:web:4fa613b099c30909d3de78',
    messagingSenderId: '706848631529',
    projectId: 'eesa-egerton',
    authDomain: 'eesa-egerton.firebaseapp.com',
    storageBucket: 'eesa-egerton.appspot.com',
    measurementId: 'G-67E18LQF5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC86QK5MOxkPEq061dX_iLKEar_Z9mavKQ',
    appId: '1:706848631529:android:3d97f94d2d6f6cdfd3de78',
    messagingSenderId: '706848631529',
    projectId: 'eesa-egerton',
    storageBucket: 'eesa-egerton.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqZYMqWiGgQXyFZdkCrNJflqEIfYpYpOY',
    appId: '1:706848631529:ios:e7e1f4cbc110c71fd3de78',
    messagingSenderId: '706848631529',
    projectId: 'eesa-egerton',
    storageBucket: 'eesa-egerton.appspot.com',
    iosClientId: '706848631529-dk79tq9b9ckv136o7t27p04llpdbgcf3.apps.googleusercontent.com',
    iosBundleId: 'com.egerton.eesa.eesa',
  );
}
